config/routes.rb
Rails.application.routes.draw do

  resources :collects

  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout' }
  
  resources :users

  root 'collects#index'

end

app/models/collect.rb
class Collect < ApplicationRecord
end

app/controllers/collects_controller.rb
class CollectsController < ApplicationController
  before_action :set_collect, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user! #, except: [:index]

  # GET /collects
  # GET /collects.json
  def index
    @collects = Collect.all
  end

  # GET /collects/1
  # GET /collects/1.json
  def show
  end

  # GET /collects/new
  def new
    @collect = Collect.new
  end

  # GET /collects/1/edit
  def edit
  end

  # POST /collects
  # POST /collects.json
  def create
    @collect = Collect.new(collect_params)

    respond_to do |format|
      if @collect.save
        format.html { redirect_to @collect, notice: 'Collect was successfully created.' }
        format.json { render :show, status: :created, location: @collect }
      else
        format.html { render :new }
        format.json { render json: @collect.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collects/1
  # PATCH/PUT /collects/1.json
  def update
    respond_to do |format|
      if @collect.update(collect_params)
        format.html { redirect_to @collect, notice: 'Collect was successfully updated.' }
        format.json { render :show, status: :ok, location: @collect }
      else
        format.html { render :edit }
        format.json { render json: @collect.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collects/1
  # DELETE /collects/1.json
  def destroy
    @collect.destroy
    respond_to do |format|
      format.html { redirect_to collects_url, notice: 'Collect was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collect
      @collect = Collect.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def collect_params
      params.require(:collect).permit(:current, :previous, :date)
    end
end

app/helpers/collects_helper.rb
module CollectsHelper
end

app/views/collects/_form.html.erb
<%= form_for(collect) do |f| %>
  <% if collect.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(collect.errors.count, "error") %> prohibited this collect from being saved:</h2>

      <ul>
      <% collect.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :current %>
    <%= f.text_field :current %>
  </div>

  <div class="field">
    <%= f.label :previous %>
    <%= f.text_field :previous %>
  </div>

  <div class="field">
    <%= f.label :date %>
    <%= f.date_select :date %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/collects/edit.html.erb
<h1>Editing Collect</h1>

<%= render 'form', collect: @collect %>

<%= link_to 'Show', @collect %> |
<%= link_to 'Back', collects_path %>

app/views/collects/new.html.erb
<h1>New Collect</h1>

<%= render 'form', collect: @collect %>

<%= link_to 'Back', collects_path %>

app/views/collects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Current:</strong>
  <%= @collect.current %>
</p>

<p>
  <strong>Previous:</strong>
  <%= @collect.previous %>
</p>

<p>
  <strong>Date:</strong>
  <%= @collect.date %>
</p>

<%= link_to 'Edit', edit_collect_path(@collect) %> |
<%= link_to 'Back', collects_path %>