config/routes.rb
Rails.application.routes.draw do

  resources :collects

  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout' }
  
  resources :users

  root 'collects#index'

end

app/helpers/layout_helper.rb
module LayoutHelper
	def navbar_brand_image
		image_tag("logos/logo-condominium.jpeg", alt: t('app.title'))
	end
	def navbar_proceedings_list
		['proceedings']
	end
	def navbar_registers_list
		['registers', 'users', 'areas','signatures','pieces','type_pieces', 'documents', 'profiles','attachments']
	end
	def navbar_brand_image_min_right
		image_tag("logos/logo-condominium.jpeg", height: '50%', width: '50%', alt: t('app.title'))
	end
	def login_governo_image
		image_tag("logos/logo-condominium.jpeg", height: '100%', width: '80%', alt: t('app.title'))
	end
	def login_sistema_image
		image_tag("logos/logo-condominium.jpeg", height: '100%', width: '75%', alt: t('app.title'))
	end
end

app/views/layouts/_footer.html.haml
.container
  .footer-content.text-center
    .row.justify-content-center
      .col-9 © 2018 - Felipe Tecnologias Ltda. Todos os direitos reservados.
      .col-9 
        = t('app.version')

app/views/layouts/_head.html.haml
= javascript_include_tag('https://use.fontawesome.com/0e2d62fd8a.js')
= javascript_include_tag('https://www.google.com/recaptcha/api.js')

%meta{content: 'text/html; charset=UTF-8', 'http-equiv': 'Content-Type'}/
%meta{name:"viewport", content:"width=device-width, initial-scale=1.0"}/

%title= "e-Prazos"


= favicon_link_tag(source='favicon.ico')

- # versão 4.0.3 tem problema de manter foco ao selecionar elemento
- # https://github.com/select2/select2/issues/4384#issuecomment-228464364
- select2_version = '4.0.2'
- flexdatalist_version = '2.2.2'

/ = stylesheet_link_tag("https://cdnjs.cloudflare.com/ajax/libs/select2/#{select2_version}/css/select2.min.css")
/ = stylesheet_link_tag("https://cdnjs.cloudflare.com/ajax/libs/jquery-flexdatalist/#{flexdatalist_version}/jquery.flexdatalist.min.css")
/ = stylesheet_link_tag("https://cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.css")
= stylesheet_link_tag(:application, media: :all)
= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

= yield(:stylesheet)
= csrf_meta_tags

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-toggleable-md.navbar-inverse
  .container
    - if user_signed_in?
      %h1.navbar-brand{title: t('app.title') }
        %a{href: root_path}
          = navbar_brand_image

    
        %button.navbar-toggler.navbar-toggler-right{ type: 'button', data: { toggle: 'collapse', target: '#navbar-toggleable', 'aria-controls': 'navbar-toggleable', 'aria-expanded': 'false', 'aria-label': t('shared.navbar.toggle_navigation') } }
          %span.navbar-toggler-icon

      %ul.navbar-nav.ml-auto
        .collapse.navbar-collapse.text-center.text-white{:id => "navbar-toggleable"}
          %ul.navbar-nav.ml-auto        
            %li.nav-item
              = link_to 'proceeding_confirmation_path', class: "nav-link #{navbar_proceedings_list.include?(controller_path)  ? 'active' : ''}" do
                %i.fa.fa-file-text.d-block.hidden-md-down{ 'aria-hidden': 'true' }
                = t('nav.proceedings')
                %br
                %br
                .navbar-active-indicator.hidden-md-down
                  %i.fa.fa-caret-up{'aria-hidden': 'true'}
            %li.nav-item
              = link_to 'registers_path', class: "nav-link #{navbar_registers_list.include?(controller_path)  ? 'active' : ''}" do
                %i.fa.fa-pencil-square.d-block.hidden-md-down{ 'aria-hidden': 'true' }
                = t('nav.registers')
                %br
                %br
                
                .navbar-active-indicator.hidden-md-down
                  %i.fa.fa-caret-up{'aria-hidden': 'true'}
            %li.nav-item
              = link_to root_path, class: 'nav-link' do
                %i.fa.fa-bar-chart.d-block.hidden-md-down{ 'aria-hidden': 'true' }
                = t('nav.reports')
                %br
                %br
            %li.nav-item
              = link_to  destroy_user_session_path, method: :delete, class: 'nav-link' do
                %i.fa.fa-sign-out.d-block.hidden-md-down{ 'aria-hidden': 'true' }
                = t('nav.exit')
                %br
                %br
    - else
      %h1.navbar-brand{title: t('app.title') }
        %a{href: root_path}
          = navbar_brand_image_min_right
.navbar-bottom-line

app/views/layouts/_ribbon.html.haml
- if Rails.env != 'production'
  .ribbon
    .sr-only
      = t("app.env.stage.label")
    %span
      = t("app.env.stage.#{Rails.env}")

app/views/layouts/_toolbar.html.haml
- if user_signed_in?
  .toolbar
    .row
      .toolbar-content.col-xl-6.col-md-12
      .toolbar-content.col-xl-6.col-md-12
        .float-right
          .float-left
            .dropdown
              %a.btn.btn-secondary2.dropdown-toggle{ href: '#!', id: 'dropdownMenuLink', 'data-toggle':'dropdown', 'aria-haspopup':'true', 'aria-expanded':'false'}
                %i.fa.fa-bell{'aria-hidden':'true'}

                - total_unread = 1
                - last_notifications = nil

                - if total_unread > 0
                  %span.notification.badge.badge-danger
                    = total_unread > 99 ? '+99' : total_unread

              .dropdown-menu{'aria-labelledby':'dropdownMenuLink'}
                - max_number_of_notifications = 5

                - if (last_notifications == nil or last_notifications.empty?)
                  %i.dropdown-item
                    = t('toolbar.notifications.empty')
                - else
                  = link_to last_notifications, root_path
                  %hr
                  = link_to root_path, class: 'dropdown-item', title: t('main.buttons.ver_todos') do
                    = 'Ver mais...'

          .float-left.ml-3
            .dropdown
              %a.btn.btn-secondary2.dropdown-toggle{ href: '#!', id: 'dropdownMenuLink', 'data-toggle':'dropdown', 'aria-haspopup':'true', 'aria-expanded':'false'}
                %i.fa.fa-user{'aria-hidden':'true'}
                - if !current_user.nil?
                  /= current_user


              .dropdown-menu{'aria-labelledby':'dropdownMenuLink'}
                %spam.dropdown-item
                  %i.fa.fa-home{'aria-hidden':'true'}
                  = link_to 'Administrador', root_path # link_to current_user.profile.description, edit_user_path(id: current_user.id)

                .dropdown-divider

                = link_to destroy_user_session_path , method: :delete, class: 'dropdown-item' do

                  %i.fa.fa-sign-out{'aria-hidden':'true'}
                  = t('toolbar.logout')

app/views/layouts/application.html.haml
!!! 5
%html{lang: 'pt-BR'}
  %head
    = render 'layouts/head'
  %body
    = render 'layouts/ribbon'
    = render 'layouts/navbar'
    .container
      -# if user_signed_in?
      = render 'layouts/toolbar'
      = yield 


  %footer
    = render 'layouts/footer'